<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="6" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="119" started-at="2022-10-05T15:49:12Z" finished-at="2022-10-05T15:49:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="119" started-at="2022-10-05T15:49:12Z" finished-at="2022-10-05T15:49:12Z">
      <class name="com.testNGFramework.BankingApplicationHardDependency">
        <test-method status="PASS" signature="lunchApplication()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="lunchApplication" duration-ms="21" started-at="2022-10-05T15:49:12Z" finished-at="2022-10-05T15:49:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method status="FAIL" signature="loginUser()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="loginUser" duration-ms="4" started-at="2022-10-05T15:49:12Z" depends-on-methods="com.testNGFramework.BankingApplicationHardDependency.lunchApplication" finished-at="2022-10-05T15:49:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login] but found [not Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login] but found [not Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testNGFramework.BankingApplicationHardDependency.loginUser(BankingApplicationHardDependency.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUser -->
        <test-method status="SKIP" signature="checkSavingAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="checkSavingAccountBalance" duration-ms="0" started-at="2022-10-05T15:49:12Z" depends-on-methods="com.testNGFramework.BankingApplicationHardDependency.loginUser" finished-at="2022-10-05T15:49:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BankingApplicationHardDependency.checkSavingAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BankingApplicationHardDependency.checkSavingAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSavingAccountBalance -->
        <test-method status="SKIP" signature="checkCurrentAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="checkCurrentAccountBalance" duration-ms="0" started-at="2022-10-05T15:49:12Z" depends-on-methods="com.testNGFramework.BankingApplicationHardDependency.checkSavingAccountBalance" finished-at="2022-10-05T15:49:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BankingApplicationHardDependency.checkCurrentAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BankingApplicationHardDependency.checkCurrentAccountBalance()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCurrentAccountBalance -->
        <test-method status="SKIP" signature="logOut()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="logOut" duration-ms="0" started-at="2022-10-05T15:49:12Z" depends-on-methods="com.testNGFramework.BankingApplicationHardDependency.checkCurrentAccountBalance" finished-at="2022-10-05T15:49:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BankingApplicationHardDependency.logOut()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BankingApplicationHardDependency.logOut()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method status="SKIP" signature="closeApplication()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225]" name="closeApplication" duration-ms="0" started-at="2022-10-05T15:49:12Z" depends-on-methods="com.testNGFramework.BankingApplicationHardDependency.logOut" finished-at="2022-10-05T15:49:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BankingApplicationHardDependency.closeApplication()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BankingApplicationHardDependency.closeApplication()[pri:0, instance:com.testNGFramework.BankingApplicationHardDependency@59494225] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.testNGFramework.BankingApplicationHardDependency -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
